### PR TITLE
[#128] Fix Scenario-2 to work with different center frequencies

### PR DESCRIPTION
**Pull request by charlesincharge**
https://github.com/agencyenterprise/neurotechdevkit/issues/128

#### Introduction

Changing the center_frequency to something outside of `5e5` changes the grid size, but the material mask for Scenario 2 is loaded from the data file and not resized to the grid size, so the code errors out.

#### Changes

This uses simple nearest-neighbors zooming (`scipy.ndimage.zoom(order=0)`) to resize to match the actual grid. To catch similar errors in the future, I have added `test_builtin.py` to test built-in scenarios.

Currently building off the https://github.com/agencyenterprise/neurotechdevkit/pull/122 branch. When that merges, I will redirect this PR at the `main` branch.

#### Behavior

Running `Scenario_2_2D` with different `center_frequency` values should work.

```python
def plot_scenario(chosen_scenario, center_frequency):
    print(f"Simulating scenario: {chosen_scenario.name}")
    scenario = chosen_scenario.value()
    scenario.center_frequency = center_frequency
    scenario.make_grid()
    scenario.compile_problem()
    scenario.render_layout()
    result = scenario.simulate_steady_state()
    result.render_steady_state_amplitudes(show_material_outlines=False)

plot_scenario(ndk.BUILTIN_SCENARIOS.SCENARIO_2_2D, 0.5e5)
```
image
image

```python
plot_scenario(ndk.BUILTIN_SCENARIOS.SCENARIO_2_2D, 1e6)
```
image
image

#### Notes
In the process of writing tests, I realized that `Scenario_0` doesn't work with a smaller `center_frequency`, e.g. `center_frequency=1e5`, because there is some grid-sizing-assumptions: https://github.com/agencyenterprise/neurotechdevkit/blob/95d9ed21711ccecf525f0abbc6d88d6b565413ed/src/neurotechdevkit/scenarios/_scenario_0.py#L126-L127

Does anyone know how that should be modified? Or should I just do the same `scipy.ndimage.zoom` to rescale that indexing?

### CODE REVIEW

**Review by NewtonSander — APPROVED** [review]
Thanks for this fix! And for the PR description, it's really well written!

**Comment by d-lucena** [comment]
This is great, thanks @charlesincharge!!
I think taking the same approach for `Scenario_0` makes sense. I think that could be added to the current PR as it fixes the same issue.

**Comment by charlesincharge** [comment]
Thanks!

Is Scenario0 a specific benchmark we should be careful not to change? (I don't see it in https://pubs.aip.org/asa/jasa/article/152/2/1003/2838380/Benchmark-problems-for-transcranial-ultrasound) @NewtonSander @d-lucena

To fix Scenario0 (for different `center_frequency`), it would be a lot cleaner if we just took out this hard-coding (instead of keeping it in & then needing to use `scipy.ndimage.zoom` to different grid sizes).

Here's the before at 500 kHz:
image

and after taking out https://github.com/agencyenterprise/neurotechdevkit/blob/95d9ed21711ccecf525f0abbc6d88d6b565413ed/src/neurotechdevkit/scenarios/_scenario_0.py#L126-L127 :

image

At different frequencies, the pixelation will look different.

**Comment by d-lucena** [comment]
hey @charlesincharge! 
You're correct about scenario 0 not existing in the benchmark paper. The main thing we want to keep is that people can compare their own results with different center frequencies.

The removal of hard-coded pieces sound good too, if that's going to be cleaner solution.

**Comment by charlesincharge** [comment]
Great, I have pushed the hard-coding removal.

**Comment by charlesincharge** [comment]
accidentally force-pushed over this (and auto-closed), but have fixed it now and will reopen.

**Pull request merged**
